### ISSUE TITLE
output coverage summary (gitlab integration)

### ISSUE THREAD

**Issue by gdesmott** [mozilla/grcov#556]
It would be great to have an easy way to output on stdout the coverage summary in a way [easily parsable by gitlab](https://docs.gitlab.com/ee/ci/pipelines/settings.html#test-coverage-parsing).

**Comment by gdesmott** [comment]
Found a workaround using `lcov`:

```
- grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "*target*"  -o lcov
- lcov -r lcov "/*" 2&> out
- grep lines out
```

And then I use `\s*lines\.*:\s*([\d\.]+%)` as regexp in gitlab as suggested here: https://www.greycastle.se/how-to-show-flutter-test-coverage-in-gitlab-ci/

**Comment by calixteman** [comment]
Any PR is welcome.
There are several examples of output so I'd say that isn't hard to do.

**Comment by gdesmott** [comment]
Would you add this as a new `summary` output type?

**Comment by calixteman** [comment]
I'm fine with `summary`.

**Comment by marco-c** [comment]
Duplicate of #468?

**Comment by gdesmott** [comment]
No, #468 is about generating a full report in the Cobertura format, while this ticket is about just producing a summary (nb of lines covered / total nb of lines) for GitLab summary.

**Comment by detly** [comment]
This is what I currently do for Gitlab. I use `xmlstarlet`, which is similar to `jq` but for XML data.

```yaml
script:
    # Coverage commands go here...
    # Extract and print percentage from Cobertura. See Gitlab issue #21549
    - >
      export COVERAGE_DEC=$(
      xmlstarlet sel -t -v "number(//coverage/@line-rate)"
      <cobertura.xml 2>/dev/null
      )
    - export COVERAGE_PCT=$(echo "100 * $COVERAGE_DEC" | bc)
    - printf "gitlab-coverage %s%%\n" "$COVERAGE_PCT"
  coverage: '/^gitlab-coverage .+%$/'
```

Full CI file is [here](https://gitlab.com/rust-test-binary/test-binary/-/blob/main/.gitlab-ci.yml).

**Comment by edmundoferreira** [comment]
I think `--summary` is a nice approach. Since I faced the same issue I can maybe share here my current Gitlab CI/CD solution.

```
.ctest:
    stage: test
    script:
        - ctest --test-dir ./build -j $(nproc) --no-tests=error --output-on-failure --output-junit ctest_junit.xml
        - mkdir ./build/coverage/
        - grcov ./build -s ./ --threads $(nproc) --branch --output-types html,cobertura,markdown -o ./build/coverage/ --ignore '/usr/include*' --ignore '*build*' --ignore '*lib*'
        - cat ./build/coverage/markdown.md
    coverage: /Total coverage:.*\s+(\d*\.?\d+\%)/
    artifacts:
        paths:
            - ./build/coverage/
        reports:
            junit: build/ctest_junit.xml
            coverage_report:
                coverage_format: cobertura
                path: ./build/coverage/cobertura.xml
```

I output as `markdown` and `cat` it to the job shell.
Then use the following regex `coverage: /Total coverage:.*\s+(\d*\.?\d+\%)/` to get the values into gitlab. This was my main driver for PR https://github.com/mozilla/grcov/pull/981.
I use `ctest` to get `junit` test information.
This also has cobertura information displayed correctly in gitlab web code editor, shown on MR.
