### ISSUE TITLE
Coverage display on codecov.io does not match locally-generated HTML report

### ISSUE THREAD

**Issue by jwodder** [mozilla/grcov#860]
I don't know whether this is a problem with grcov or Codecov, but you seem more accessible, so I'll start here.

I am attempting to set up coverage reporting of [my Rust project](https://github.com/jwodder/ghrepo-rust) using grcov and codecov.io.  When I generate HTML coverage reports locally like so:

```sh
export RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }-Cinstrument-coverage"
cargo build
export LLVM_PROFILE_FILE="target/coverage/prof/%p-%m.profraw"
cargo test

grcov \
    --source-dir . \
    --binary-path target/debug \
    --branch \
    --excl-start 'mod tests \{' \
    --ignore 'tests/*' \
    -t html \
    -o target/coverage/html \
    target/coverage/prof
```

then the coverage is shown as 88.61%, and the report (mostly) makes sense.  However, when I upload a report to codecov from GitHub Actions with the following workflow:

```yaml
name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - '1.60'
          - stable
          - beta
          - nightly
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure Git identity
        # Needed for a couple tests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'ghactions@nil.nil'

      - name: Install Rust
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup component add llvm-tools-preview
          cargo install grcov

      - name: Build crate
        run: cargo build --verbose
        env:
          RUSTFLAGS: "-Cinstrument-coverage"

      - name: Test crate
        run: cargo test --verbose
        env:
          LLVM_PROFILE_FILE: "target/coverage/prof/%p-%m.profraw"
          RUSTFLAGS: "-Cinstrument-coverage"

      - name: Create coverage report
        run: |
         grcov \
           --source-dir . \
           --binary-path target/debug \
           --branch \
           --excl-start 'mod tests \{' \
           --ignore 'tests/*' \
           -t lcov \
           -o lcov.info \
           target/coverage/prof

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: false
```

then the coverage is shown as 48.21%, and much of the report does not match the HTML report, nor does it make much sense.

For example, compare this section of the HTML report:

<img width="908" alt="Screen Shot 2022-07-08 at 09 57 22" src="https://user-images.githubusercontent.com/98207/178007654-c5302b68-7435-4365-928b-6de7966292d3.png">

with the corresponding section in codecov's report:

<img width="903" alt="Screen Shot 2022-07-08 at 09 57 44" src="https://user-images.githubusercontent.com/98207/178007705-4b874263-163a-4432-b75e-49358261b97d.png">

Another example: In the HTML report, all of the lines shown below are neither hit nor missed, yet codecov shows a mixture of hit & missed lines, including some of both in the comments!

<img width="793" alt="Screen Shot 2022-07-08 at 09 58 20" src="https://user-images.githubusercontent.com/98207/178007878-e9d546d5-1d48-4787-b8e1-a55e61df7871.png">

In addition, I previously had my tests in my `src/lib.rs` file but later moved them to `tests/`.  When they were in `src/lib.rs`, I was able to get the HTML report to show the tests as neither hit nor missed, yet Codecov showed the tests as largely missed, with some hits thrown in.

You can find the report uploaded to codecov for the "stable" run of [this commit](https://github.com/jwodder/ghrepo-rust/tree/9a79da60f3445488f0eed8286d595448d8920e9a) here: <https://github.com/mozilla/grcov/files/9072729/build.txt>.
